version: '3.8'

services:
    #MYSQL
    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'laravel_inertia'
        volumes:
            - mysqldata:/var/lib/mysql
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 10

volumes:

    mysqldata:
